import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
    githubId: { type: String, required: true, unique: true },
    github: { type: String, required: true },
    displayName: { type: String },
    email: { type: String },
    avatarUrl: { type: String },

    // did:key  — generated by key-did-provider-ed25519 (Ceramic / Protocol Labs)
    // Example:  did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK
    did: { type: String, unique: true, sparse: true },

    // CID returned by @web3-storage/w3up-client (Storacha / Protocol Labs)
    // Points to the identity document JSON on IPFS
    ipfsCID: { type: String },

    // Resolved W3C DID document (cached from IPFS for fast API responses)
    didDocument: { type: Object },

    // Optional Flow blockchain wallet
    wallet: { type: String, default: null },

    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
});

userSchema.pre('save', function (next) {
    this.updatedAt = Date.now();
    next();
});

export default mongoose.model('User', userSchema);
